C/C/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage),
    path('about/', views.about),
    path('posts/', include('posts.urls'))
]

C/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.posts_list, name='list'),
    path('<slug:slug>', views.post_page, name='page'),
]

C/posts/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=75)
    body = models.TextField()
    slug = models.SlugField()
    date = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.title

C/C/views.py
from django.shortcuts import render
from django.http import HttpResponse

def homepage(request):
    return render(request, 'home.html' )
    # return HttpResponse('Hoooray!!!, i am glad to be a pro in this sector!')


def about(request):
    return render(request, 'about.html')
    # return HttpResponse('My About page')

C/posts/views.py
from django.shortcuts import render
from .models import Post

# Create your views here.
def posts_list(request):
    posts = Post.objects.all().order_by('-date')
    return render(request, 'posts/post_list.html', {'posts': posts})
def post_page(request, slug):
    post = Post.objects.get(slug=slug)
    return render(request, 'posts/post_page.html', {'post': post})

C/posts/templates/posts/post_list.html
{% extends "layout.html" %}
{% block title %}
        Post 
{% endblock %}
{% block content %}
<section>
  <h2>posts</h2>

  {% for post in posts %}
    <article class = "post">
    </h2>
        <a href="{% url 'posts:page' slug=post.slug %}">
            {{ post.title }}
        </a>
    </h2>
    <p>{{ post.date }}</p>
    <p>{{ post.body }}</p>
    </article>
  {% endfor %}
</section>
{% endblock %}

C/posts/templates/posts/post_page.html
{% extends "layout.html" %} {% block title %} {{ post.title }} {% endblock %} 
{% block content %}
<section>
  <h2>{{ post.title }}</h2>
  <p>{{ post.date }}</p>
  <p>{{ post.body }}</p>
</section>
{% endblock %}

C/templates/about.html
{% extends "layout.html" %} {% block title %} About page {% endblock %} {% block content %}
<h2>Home</h2>
<p>Checkout my <a href="about/">Home page</a></p>
{% endblock %}

C/templates/home.html
{% extends "layout.html" %} {% block title %} Home page {% endblock %} 
{% block content %}
<h2>Home</h2>
<p>Checkout my <a href="about/">About page</a></p>
{% endblock %}

C/templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %} Django App {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/style.css'%}" />
    <script src="{% static 'js/main.js' %}" defer></script>
  </head>
  <body>
    <nav>
      <a href="/">
        <span role = "img" arial-label ="Home">🏠</span>
      </a> | <a href="/about">😂</a> |
      <a href="{% url "posts:list" %}">📰</a>
    </nav>
    <main>{% block content %} {% endblock %}</main>
  </body>
</html>